### ISSUE TITLE
The expat submodule seems to be unavailable

### ISSUE THREAD

**Issue by h2so5** [strophe/libstrophe#1]
May I suggest updating the submodule repository?
e.g. https://github.com/coapp-packages/expat

Thanks for the great library!

**Comment by changeway** [comment]
I add libstrophe to OpenWRT project packages, I tried to use latest commit for new features. But this old .gitmodules stopping the make process. OpenWRT packages could select expat or libxml2 as XML library for libstrophe. But this submodule is unavailable. Could it possible to remove this expat submodule? Thanks

**Comment by pasis** [comment]
Expat submodule is removed. We can't rely on unofficial repos. We need to find better way than providing one monolithic source tree with all 3rd-part dependencies. This affects only such platforms as windows(visual studio), android(ndk-build), ios.
