### ISSUE TITLE
Send PUSH notification to Google Firebase server

### ISSUE THREAD

**Issue by pengweichu** [strophe/libstrophe#112]
Hi, I'm new to XMPP, I would like to use libstrophe to send the PUSH notification to google firebase server, 
I'm using C++, in the C++ wrapper strophepp.h I didn't find any TLS options, it's possible use connect to server over TLS by C++ wrapper ?

Thanks

**Comment by pasis** [comment]
Hello,

Unfortunately, C++ wrapper is unfinished and lacking new features added in libstrophe-0.9.x. One class is completely missed.

However, you can use C version of libstrophe without limitations. There are opensource C++ projects that create own wrappers for their needs. I can search for them if you're interested.

libstrophe establishes TLS implicitly. By default, it's established every time when server supports it. Starting with libstrophe version 0.9 you can control TLS establishing via connection flags. See https://github.com/strophe/libstrophe/blob/master/examples/basic.c for example. With `XMPP_CONN_FLAG_MANDATORY_TLS` flag libstrophe always establishes TLS or fails if it's impossible.

I'm not familiar with PUSH notification to Google Firebase server, so can't help with it right now.

**Comment by pasis** [comment]
Close due to inactivity.
