### ISSUE TITLE
Provide new bool parameters use_ssl and use_tls on xmpp_connect_client

### ISSUE THREAD

**Issue by vit1251** [strophe/libstrophe#114]
Require connect parameters use_ssl and use_tls for using a different type of SSL and TLS connection or even without encryption for debug purposes.

**Comment by pasis** [comment]
Such a functionality won't be added to master branch. Moreover, libstrophe disables SSL/TLSv1: https://github.com/strophe/libstrophe/blob/master/src/tls_openssl.c#L107 .

By default, libstrophe tries to establish TLS when server supports it and there is no error during initialisation of a tls context. Fact of successful TLS establishing can be checked via `xmpp_conn_is_secured()`. To control this process you can use the connection flags `XMPP_CONN_FLAG_DISABLE_TLS` and `XMPP_CONN_FLAG_MANDATORY_TLS` (see https://github.com/strophe/libstrophe/blob/master/examples/basic.c).

If you still need to control SSL/TLS versions I can provide a branch with such a functionality, but without merging to master or further porting new features to the branch.

**Comment by vit1251** [comment]
Compile with flags is simple operation but ... you should have compile but now I provide package with simple dependencies from dist package in this case I can not any compile operation.

Now I compile without TLS but I can not implement it in package dist dependencie and I should include (embed) your source code in my package it does not good.

In any case thanks for you attention.

**Comment by pasis** [comment]
Closing issue.

`XMPP_CONN_FLAG_DISABLE_TLS` and `XMPP_CONN_FLAG_MANDATORY_TLS` are "run-time" flags and you don't have to rebuild library in order to control TLS.

**Comment by vit1251** [comment]
Thanks for answer.
