### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by diprom** [strophe/libstrophe#116]
Try this - get leaks.   

```
/* basic.c
** libstrophe XMPP client library -- basic usage example
**
** Copyright (C) 2005-2009 Collecta, Inc.
**
**  This software is provided AS-IS with no warranty, either express
**  or implied.
**
** This program is dual licensed under the MIT and GPLv3 licenses.
*/

#include <stdio.h>
#include <string.h>

#include "libstrophe\strophe.h"
#pragma comment(lib,"ws2_32.lib") //Winsock Library
#pragma comment(lib,"libeay32.lib") //libeay32.lib  Library
#pragma comment(lib,"ssleay32.lib") //ssleay32.lib  Library
/* hardcoded TCP keepalive timeout and interval */
#define KA_TIMEOUT 60
#define KA_INTERVAL 1

#define _CRTDBG_MAP_ALLOC
#include <cstdlib>
#include <crtdbg.h>
#include <Windows.h>
#ifdef _DEBUG
    #define new new ( _NORMAL_BLOCK , __FILE__ , __LINE__ )
    // Replace _NORMAL_BLOCK with _CLIENT_BLOCK if you want the
    // allocations to be of _CLIENT_BLOCK type
#else
    #define DBG_NEW new
#endif



/* define a handler for connection events */
void conn_handler(xmpp_conn_t * const conn, const xmpp_conn_event_t status,
                  const int error, xmpp_stream_error_t * const stream_error,
                  void * const userdata)
{
    xmpp_ctx_t *ctx = (xmpp_ctx_t *)userdata;
    int secured;

    if (status == XMPP_CONN_CONNECT) {
        fprintf(stderr, "DEBUG: connected\n");
        secured = xmpp_conn_is_secured(conn);
        fprintf(stderr, "DEBUG: connection is %s.\n",
                secured ? "secured" : "NOT secured");
        xmpp_disconnect(conn);
    }
    else {
        fprintf(stderr, "DEBUG: disconnected\n");
        xmpp_stop(ctx);
    }
}




int main(int argc, char **argv)
{
   xmpp_ctx_t *ctx;
    xmpp_conn_t *conn;
    xmpp_log_t *log;
    char *jid, *pass, *host = NULL;
    long flags = 0;
    int tcp_keepalive = 0;
   
	_CrtMemState _ms; 

		/*_CrtSetReportMode( _CRT_WARN, _CRTDBG_MODE_FILE ); // enable file output
			_CrtSetReportFile( _CRT_WARN, _CRTDBG_FILE_STDOUT ); // set file to stdout
			
			_CrtMemCheckpoint(&_ms); // now forget about objects created before
*/


    jid = "0000";
    pass = "0000";
        host = "127.0.0.1";


    xmpp_initialize();
	
   
    log = xmpp_get_default_logger(XMPP_LEVEL_DEBUG); 
    ctx = xmpp_ctx_new(NULL, log);

  /*
    conn = xmpp_conn_new(ctx);


    xmpp_conn_set_flags(conn, flags);

    if (tcp_keepalive) xmpp_conn_set_keepalive(conn, KA_TIMEOUT, KA_INTERVAL);


    xmpp_conn_set_jid(conn, jid);
    xmpp_conn_set_pass(conn, pass);


    xmpp_connect_client(conn, host, 10012, conn_handler, ctx);


    //xmpp_run2(ctx);

    
	xmpp_disconnect(conn);
	conn_disconnect(conn) ;
	xmpp_conn_release(conn);
	*/

    xmpp_ctx_free(ctx);

	
    xmpp_shutdown();
	_CrtMemDumpAllObjectsSince(&_ms); 
		

	_CrtDumpMemoryLeaks();
    return 0;
}
```

**Comment by diprom** [comment]
OK, no leaks - bad sourse

**Comment by diprom** [comment]
change ctx.c

void xmpp_free(const xmpp_ctx_t * const ctx, void *p)
{
    void* k = NULL;
	if (!ctx) return;
	if (!ctx->mem) return;
	k =  ctx->mem->userdata;
	if (k)
	{
		ctx->mem->free(p, k);
		k = NULL;
	}
	if (p) {free(p);p=NULL;}
}

**Comment by pasis** [comment]
your example is equivalent to the next one:
```
#include <strophe.h>

int main(int argc, char **argv)
{
    xmpp_ctx_t *ctx;
    xmpp_log_t *log;

    xmpp_initialize();

    log = xmpp_get_default_logger(XMPP_LEVEL_DEBUG);
    ctx = xmpp_ctx_new(NULL, log);

    xmpp_ctx_free(ctx);

    xmpp_shutdown();

    return 0;
}
```
Valgrind doesn't detect memory leaks:
```
$ valgrind --leak-check=full ./a.out 
==3627== Memcheck, a memory error detector
==3627== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==3627== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==3627== Command: ./a.out
==3627== 
==3627== 
==3627== HEAP SUMMARY:
==3627==     in use at exit: 0 bytes in 0 blocks
==3627==   total heap usage: 2,852 allocs, 2,852 frees, 103,452 bytes allocated
==3627== 
==3627== All heap blocks were freed -- no leaks are possible
==3627== 
==3627== For counts of detected and suppressed errors, rerun with: -v
==3627== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
What tls module do you use? OpenSSL is recommended.

`xmpp_free()` from your 2nd comment is incorrect and there is no problem with the current implementation.

**Comment by diprom** [comment]
Спасибо, Дмитрий.

Но если вы увидите в диспетчере задач память будет неуклонно расти, если сделать вот что:

сделайте цикл на connect соединений (50-60 клиентов) с простым открытым серверным сокетом с 1 ctx, я работал с SSL.

libstrophe будет скидывать соединение через 1-2 сек, т.к. не ответа хендшейка. Если использовать стандартный xmpp_free,он

не все освободит. Модернизированный мой - работает, память не растет.

SSL версия , одна из последних, https://github.com/mhils/libxml2-win-binaries/releases


void xmpp_free(const xmpp_ctx_t * const ctx, void *p)
{
void* k = NULL;
if (!ctx) return;
if (!ctx->mem) return;
k =  ctx->mem->userdata;
if (k)
{
ctx->mem->free(p, k);
k = NULL;
}
if (p)
{
free(p);
p=NULL;
}
}

Еще модернизированный event, который позволяет "удалить на горячую" из списка conn.

int xmpp_conn_release2(void** conn)
{
int u = 0;
if (!conn  && !*conn) return -1;
u = xmpp_conn_release((xmpp_conn_t *)*conn);
if (u==1)
*conn = NULL;
return u;
}



void xmpp_run_once(xmpp_ctx_t *ctx, const unsigned long timeout)
{
    xmpp_connlist_t *connitem = NULL;
    xmpp_conn_t *conn;
    fd_set rfds, wfds;
    sock_t max = 0;
    int ret;
    struct timeval tv;
    xmpp_send_queue_t *sq, *tsq;
    int towrite;
    char buf[4096];
    uint64_t next;
    uint64_t usec;
    int tls_read_bytes = 0;

    if (ctx->loop_status == XMPP_LOOP_QUIT) return;

    /* send queued data */
    connitem = ctx->connlist;
    while (connitem) {
        conn = connitem->conn;
        if (conn->state != XMPP_STATE_CONNECTED) {
            connitem = connitem->next;
            continue;
        }

        /* if we're running tls, there may be some remaining data waiting to
         * be sent, so push that out */
        if (conn->tls) {
            ret = tls_clear_pending_write(conn->tls);

            if (ret < 0 && !tls_is_recoverable(tls_error(conn->tls))) {
                /* an error occurred */
                xmpp_debug(ctx, "xmpp", "Send error occurred, disconnecting.");
                conn->error = ECONNABORTED;
                conn_disconnect(conn);
            }
        }

        /* write all data from the send queue to the socket */
        sq = conn->send_queue_head;
        while (sq) {
            towrite = sq->len - sq->written;

            if (conn->tls) {
                ret = tls_write(conn->tls, &sq->data[sq->written], towrite);
                if (ret < 0 && !tls_is_recoverable(tls_error(conn->tls)))
                    conn->error = tls_error(conn->tls);
            } else {
                ret = sock_write(conn->sock, &sq->data[sq->written], towrite);
                if (ret < 0 && !sock_is_recoverable(sock_error()))
                    conn->error = sock_error();
            }
            if (ret > 0 && ret < towrite)
                sq->written += ret; /* not all data could be sent now */
            if (ret != towrite)
                break; /* partial write or an error */

            /* all data for this queue item written, delete and move on */
            xmpp_free2(ctx, (void**)&sq->data);
            tsq = sq;
            sq = sq->next;
            conn->send_queue_len--;
            xmpp_free2(ctx, (void**)&tsq);

            /* pop the top item */
            conn->send_queue_head = sq;
            /* if we've sent everything update the tail */
            if (!sq) conn->send_queue_tail = NULL;
        }

        /* tear down connection on error */
        if (conn->error) {
            /* FIXME: need to tear down send queues and random other things
             * maybe this should be abstracted */
            xmpp_debug(ctx, "xmpp", "Send error occurred, disconnecting.");
            conn->error = ECONNABORTED;
            conn_disconnect(conn);
        }

        connitem = connitem->next;
    }

    /* reset parsers if needed */
    for (connitem = ctx->connlist; connitem; connitem = connitem->next) {
        if (connitem->conn->reset_parser)
            conn_parser_reset(connitem->conn);
    }


    /* fire any ready timed handlers, then make sure we don't wait past
       the time when timed handlers need to be called */
    next = handler_fire_timed(ctx);

    usec = ((next < timeout) ? next : timeout) * 1000;
    tv.tv_sec = (long)(usec / 1000000);
    tv.tv_usec = (long)(usec % 1000000);

    FD_ZERO(&rfds);
    FD_ZERO(&wfds);

    /* find events to watch */
    connitem = ctx->connlist;
    while (connitem) {
        conn = connitem->conn;

        switch (conn->state) {
        case XMPP_STATE_CONNECTING:
            /* connect has been called and we're waiting for it to complete */
            /* connection will give us write or error events */

            /* make sure the timeout hasn't expired */
            if (time_elapsed(conn->timeout_stamp, time_stamp()) <=
                conn->connect_timeout)
                FD_SET(conn->sock, &wfds);
            else {
                conn->error = ETIMEDOUT;
                xmpp_info(ctx, "xmpp", "Connection attempt timed out.");
                conn_disconnect(conn);
            }
            break;
        case XMPP_STATE_CONNECTED:
            FD_SET(conn->sock, &rfds);
            if (conn->send_queue_len > 0)
                FD_SET(conn->sock, &wfds);
            break;
        case XMPP_STATE_DISCONNECTED:
            /* do nothing */
        default:
            break;
        }

        /* Check if there is something in the SSL buffer. */
        if (conn->tls)
            tls_read_bytes += tls_pending(conn->tls);

        if (conn->state != XMPP_STATE_DISCONNECTED && conn->sock > max)
            max = conn->sock;

        connitem = connitem->next;
    }

    /* check for events */
    if (max > 0)
        ret = select(max + 1, &rfds,  &wfds, NULL, &tv);
    else {
        if (timeout > 0)
            _sleep(timeout);
        return;
    }

    /* select errored */
    if (ret < 0) {
        if (!sock_is_recoverable(sock_error()))
            xmpp_error(ctx, "xmpp", "event watcher internal error %d",
                       sock_error());
        return;
    }

    /* no events happened */
    if (ret == 0 && tls_read_bytes == 0) return;

    /* process events */
    connitem = ctx->connlist;
    while (connitem)
{
        conn = connitem->conn;
        switch (conn->state)
{
        case XMPP_STATE_CONNECTING:
            if (FD_ISSET(conn->sock, &wfds)) {
                /* connection complete */

                /* check for error */
                ret = sock_connect_error(conn->sock);
                if (ret != 0) {
                    /* connection failed */
                    xmpp_debug(ctx, "xmpp", "connection failed, error %d", ret);
                    conn_disconnect(conn);
                    break;
                }

                conn->state = XMPP_STATE_CONNECTED;
                xmpp_debug(ctx, "xmpp", "connection successful");
                conn_established(conn);
            }

            break;
        case XMPP_STATE_CONNECTED:
            if (FD_ISSET(conn->sock, &rfds) || (conn->tls && tls_pending(conn->tls))) {
                if (conn->tls) {
                    ret = tls_read(conn->tls, buf, 4096);
                } else {
                    ret = sock_read(conn->sock, buf, 4096);
                }

                if (ret > 0) {
                    ret = parser_feed(conn->parser, buf, ret);
                    if (!ret) {
                        /* parse error, we need to shut down */
                        /* FIXME */
                        xmpp_debug(ctx, "xmpp", "parse error, disconnecting");
                        conn_disconnect(conn);
                    }
                } else {
                    if (conn->tls) {
                        if (!tls_is_recoverable(tls_error(conn->tls))) {
                            xmpp_debug(ctx, "xmpp", "Unrecoverable TLS error, %d.", tls_error(conn->tls));
                            conn->error = tls_error(conn->tls);
                            conn_disconnect(conn);
                        }
                    } else {
                        /* return of 0 means socket closed by server */
                        xmpp_debug(ctx, "xmpp", "Socket closed by remote host.");
                        conn->error = ECONNRESET;
                        conn_disconnect(conn);
                    }
                }
            }

            break;

            /* do nothing */
        default:
            break;
        }
if (conn->state == XMPP_STATE_DISCONNECTED)
{
xmpp_conn_release2((void**)&conn);
connitem = ctx->connlist;
}
if (connitem)
connitem = connitem->next;
    }

    /* fire any ready handlers */
    handler_fire_timed(ctx);
}

**Comment by diprom** [comment]
Есть ли у вас скомпилированные lib и dll libstrophe? Может мой Visual Studio 2012 что-то не так делает? Я доложил проект libstrophe и libxml2.


________________________________
От: Dmitry Podgorny <notifications@github.com>
Отправлено: 31 января 2018 г. 12:38
Кому: strophe/libstrophe
Копия: diprom; Author
Тема: Re: [strophe/libstrophe] memory leaks (#116)


your example is equivalent to the next one:

#include <strophe.h>

int main(int argc, char **argv)
{
    xmpp_ctx_t *ctx;
    xmpp_log_t *log;

    xmpp_initialize();

    log = xmpp_get_default_logger(XMPP_LEVEL_DEBUG);
    ctx = xmpp_ctx_new(NULL, log);

    xmpp_ctx_free(ctx);

    xmpp_shutdown();

    return 0;
}


Valgrind doesn't detect memory leaks:

$ valgrind --leak-check=full ./a.out
==3627== Memcheck, a memory error detector
==3627== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==3627== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==3627== Command: ./a.out
==3627==
==3627==
==3627== HEAP SUMMARY:
==3627==     in use at exit: 0 bytes in 0 blocks
==3627==   total heap usage: 2,852 allocs, 2,852 frees, 103,452 bytes allocated
==3627==
==3627== All heap blocks were freed -- no leaks are possible
==3627==
==3627== For counts of detected and suppressed errors, rerun with: -v
==3627== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)


What tls module do you use? OpenSSL is recommended.

xmpp_free() from your 2nd comment is incorrect and there is no problem with the current implementation.

**Comment by diprom** [comment]
Со стандартными вызовами - скачанный


int main(int argc, char **argv)
{
   xmpp_ctx_t *ctx;
    xmpp_conn_t *conn=NULL;
    xmpp_log_t *log;
    char *jid, *pass, *host = NULL;
    long flags = 0;
    int tcp_keepalive = 0;

_CrtMemState _ms;

/*_CrtSetReportMode( _CRT_WARN, _CRTDBG_MODE_FILE ); // enable file output
_CrtSetReportFile( _CRT_WARN, _CRTDBG_FILE_STDOUT ); // set file to stdout
_CrtMemCheckpoint(&_ms); // now forget about objects created before
*/


    jid = "0000";
    pass = "0000";
        host = "127.0.0.1";


    xmpp_initialize();

    log = xmpp_get_default_logger(XMPP_LEVEL_DEBUG);
    ctx = xmpp_ctx_new(NULL, log);


    conn = xmpp_conn_new(ctx);
xmpp_conn_release(conn);

    xmpp_ctx_free(ctx);


    xmpp_shutdown();

xmlCleanupParser () ;

_CrtMemDumpAllObjectsSince(&_ms);

//_CrtDumpMemoryLeaks();
    return 0;
}



"leaks.exe" (Win32). Загружено "D:\Projects\TerminalMCHS\leaks\leaks - копия\Debug\leaks.exe". Символы загружены.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\ntdll.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\kernel32.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\KernelBase.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\advapi32.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\msvcrt.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\sechost.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\rpcrt4.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\sspicli.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\cryptbase.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\msvcr110d.dll". Символы загружены.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\ws2_32.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\nsi.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "D:\Projects\TerminalMCHS\leaks\leaks - копия\Debug\libeay32.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\gdi32.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\user32.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\lpk.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\usp10.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\msvcr100.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "D:\Projects\TerminalMCHS\leaks\leaks - копия\Debug\ssleay32.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\imm32.dll". Невозможно найти или открыть PDB-файл.
"leaks.exe" (Win32). Загружено "C:\Windows\SysWOW64\msctf.dll". Невозможно найти или открыть PDB-файл.
Dumping objects ->
{88} normal block at 0x0048EC00, 16 bytes long.
 Data: <      H         > 01 00 00 00 98 EA 48 00 00 00 00 00 FF FF FF FF
{87} normal block at 0x0048EBB0, 16 bytes long.
 Data: <      H         > 01 00 00 00 98 EA 48 00 00 00 00 00 FF FF FF FF
{85} normal block at 0x0048EAF0, 128 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
{84} normal block at 0x0048EA98, 24 bytes long.
 Data: <      H         > 02 00 00 00 E0 E6 48 00 00 00 00 00 20 00 00 00
{83} normal block at 0x0048EA08, 28 bytes long.
 Data: <@ H             > 40 EA 48 00 FF FF FF FF 00 00 00 00 00 00 00 00
Object dump complete.
Программа "[39584] leaks.exe" завершилась с кодом 0 (0x0).




Если использовать код ниже, то утечек нет. Проблема в соединении.


int main(int argc, char **argv)
{
   xmpp_ctx_t *ctx;
    xmpp_conn_t *conn=NULL;
    xmpp_log_t *log;
    char *jid, *pass, *host = NULL;
    long flags = 0;
    int tcp_keepalive = 0;

_CrtMemState _ms;

/*_CrtSetReportMode( _CRT_WARN, _CRTDBG_MODE_FILE ); // enable file output
_CrtSetReportFile( _CRT_WARN, _CRTDBG_FILE_STDOUT ); // set file to stdout
_CrtMemCheckpoint(&_ms); // now forget about objects created before
*/


    jid = "0000";
    pass = "0000";
        host = "127.0.0.1";


    xmpp_initialize();

    log = xmpp_get_default_logger(XMPP_LEVEL_DEBUG);
    ctx = xmpp_ctx_new(NULL, log);
    xmpp_ctx_free(ctx);
    xmpp_shutdown();
xmlCleanupParser () ;
_CrtMemDumpAllObjectsSince(&_ms);

//_CrtDumpMemoryLeaks();
    return 0;
}

**Comment by pasis** [comment]
Официальных windows бинарников для libstrophe нет, потому что на проекте нет windows ментейнера (можете попробовать свои силы ;)).

Проверка соединений, как вы говорили, займет некоторое время. Пока что давайте разберемся с `xmpp_free()`. В чем проблема предложенного варианта (см. коментарии в коде):
```
void xmpp_free(const xmpp_ctx_t * const ctx, void *p)
{
    void* k = NULL;
    if (!ctx) return;
    if (!ctx->mem) return;
    /* Обычно userdata равен NULL, поэтому в вашем варианте тело первого условия
       не выполняется. Иначе, вы бы получили двойное освобождение памяти потенциально
       разными аллокаторами. */
    k =  ctx->mem->userdata;
    if (k)
    {
        ctx->mem->free(p, k);
        /* k, как и p далее, - переменные на стеке и нет смысла их обнулять вконце */
        k = NULL;
    }
    /* Использовать stdlib аллокатор здесь нельзя. Вся идея ctx->mem в том,
        что пользователь передает свой аллокатора в xmpp_ctx_new(). По умолчанию,
        libstrophe использует stdlib аллоктаор (см. _malloc(), _free() в ctx.c) и только
        поэтому этот код работает. Но перестанет, когда пользователь передаст свой
        аллокатор */
    if (p) {free(p);p=NULL;}
}
```
Кроме указанных замечаний могу сказать, что предложенный `xmpp_free()` выполняет идентичные действия с оригинальным вариантом, когда используется стандартный аллокатор. Т.е. просто вызывается `free(p)` и никаких дополнительных действий. В более краевых случаях предложенный вариант приведет к некорректому поведению библиотеки.

**Comment by diprom** [comment]
Спасибо большое за комментарии. Xmpp_free я бы не переделывал,но так как была очень большая утечка памяти даже в стандартных примерах, я пошел на это. Тем более, как и писал, в цикле соединений, эта проблема становится явной, по крайней мере в среде Windows.

Посмотрите еще тот код для event.c в процедуре, который позволяет удалить соединение из списка, актуально для цикла, когда происходит disconnect.

void xmpp_run_once(xmpp_ctx_t *ctx, const unsigned long timeout):

в конце добавлено

  default:
            break;
        }
                if (conn->state == XMPP_STATE_DISCONNECTED)
                {
                        xmpp_conn_release(conn);
                        connitem = ctx->connlist;
                }
                if (connitem)
                        connitem = connitem->next;
    }

    /* fire any ready handlers */
    handler_fire_timed(ctx);
}

**Comment by pasis** [comment]
Short summary of the above discussion: xmpp_free() won't be changed; there is reported memory leak with scenario when 50-60 xmpp_conn_t objects connect to just listening TCP socket and as result fail. I haven't checked the scenario though.

What version do you use? These leaks are libstrophe issues, but it's unclear where they happen. At least 1 looks similar to already fixed one. Also, if you build libstrophe with `-g3` you'll see much helpful info.

I'll try to run your code and see what I'll find.

**Comment by jubalh** [comment]
Hey @pasis !
Thanks for summoning up the discussion.

And even more thanks for the PRs! Highly appreciated.

**Comment by pasis** [comment]
@sjaeckel and me tried to find memory leaks in scenario of multiple connections. But we didn't find any problem with libstrophe. There might be errors in the code that used libstrophe.

Closing this ticket.
