### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by jogzug7** [strophe/libstrophe#117]
Since the last official release, many bugs have been fixed and improvements being made. How about a new release? At least a beta? Thanks!

**Comment by thinred** [comment]
On behalf of the Debian package maintainers, I also request this.

**Comment by pasis** [comment]
Please, check the latest master. If there is no problem with it I'll release 0.9.2.

**Comment by pasis** [comment]
0.9.2 released, see https://github.com/strophe/libstrophe/releases
