### ISSUE TITLE
Problems with status and error codes in the connection handler

### ISSUE THREAD

**Issue by matisszilard** [strophe/libstrophe#122]
Description:

The strophe responds with same status and error codes for different cases. 
Ex.: The status code is XMPP_CONN_DISCONNECT and the error code is 0 for cases:
*  The client is connecting to a xmpp server with invalid credentials.
*  The client is connecting to a non xmpp server. After creating the socket communication, the strophe sends back status XMPP_CONN_DISCONNECT and end error code 0. It should be the XMPP_CONN_FAIL status code and the corresponding error code.
The XMPP_CONN_DISCONNECT in line https://github.com/strophe/libstrophe/blob/master/src/event.c#L243, when the strophe cleans up the remaining resources. The error code for the connection is not set.

Steps to reproduce:

1. Connecting to a non xmpp server

*  Create a connection to a NON XMPP server
*  Start the connection
*  The strophe responds in the connection handler callback with status XMPP_CONN_DISCONNECT and error code 0

Tested on: macOS (10.13.3)

Is it possible to handle the mentioned situations in the latest release of the strophe library?
Is it possible to request the root cause of the connection failure? ex.: check if the socket communication or the authentication failed

**Comment by pasis** [comment]
Closing this ticket and leave #123 to track the issue.
