### ISSUE TITLE
Unable to create TLS connection

### ISSUE THREAD

**Issue by vit1251** [strophe/libstrophe#124]
Try to create new one connection and receive error message

```
conn DEBUG Couldn't start TLS! error -3 tls_error 5
```

**Comment by vit1251** [comment]
My investigation is complete.
Error 5 in SSL is result of close connection in underling OpenSSL BIO (OpenSSL BIO is wrap classic socket).

libstrophe should proper handle error (close connection) in this case.

You may handle this proper by close connection and delivery message about error in some error handler in next version.

**Comment by pasis** [comment]
When such an errors occurs, libstrophe closes connection and calls user's conn_handler() with XMPP_CONN_DISCONNECT event.

Closing this ticket.
