### ISSUE TITLE
do you know libstrophe how connect to openfire server

### ISSUE THREAD

**Issue by killwjh** [strophe/libstrophe#125]
i tried many times, but there were always existing some errors that i did't know exactly fuck what they  were, could you give me a example of a demo
thanks everone!

**Comment by pasis** [comment]
Sorry, I can't answer for such an abstract question. Libstrophe provides examples in [exmaples/](https://github.com/strophe/libstrophe/tree/master/examples) directory. Check basic.c for connect/disconnect examples or bot.c for receiving/sending messages.

If you have libstrophe logs (for example, output of examples/basic), re-open the issue and I can help to determine where it fails.
