### ISSUE TITLE
libstrophe crash caused by SIGPIPE signal

### ISSUE THREAD

**Issue by matisszilard** [strophe/libstrophe#127]
The libstrophe library crashed on iOS caused by a SIGPIPE signal.

Please see the following scenario:

- Connect iOS simulator to WifiA
- Start application, request data via XMPP
- Turn off the screen of the iOS simulator
- Change wifi to WifiB
- Unlock screen
- App will crash caused by a SIGPIPE signal

Related logs:

```
[Trace] : Libstrophe Log - [tls], msg [error=5 errno=60]
[Trace] : Libstrophe Log - [xmpp], msg [Unrecoverable TLS error, 5.]
[Trace] : Libstrophe Log - [xmpp], msg [Closing socket.]
[Trace] : Libstrophe Log - [tls], msg [error=5 errno=32]
[Debug] : xmpp_connection_handler - Connection Closed with error code [3]
(lldb) bt
* thread #16, stop reason = signal SIGPIPE
  * frame #0: 0x0000000114598bdc libsystem_pthread.dylib`start_wqthread
```

Disabling SIGPIPE solves the issue:

```c++
int set = 1;
setsockopt(sock, SOL_SOCKET, SO_NOSIGPIPE, (void *)&set, sizeof(int));
```

Question:

How should the libstrophe library handle the SIGPIPE properly?

Connected blog:

https://badrit.com/blog/2010/11/30/ignore-sigpipe-signal-on-ios#.W5ZGTC2B0sl

Connected issues:

https://github.com/strophe/libstrophe/issues/113
https://github.com/strophe/libstrophe/issues/124

**Comment by matisszilard** [comment]
Thanks for the information.

Maybe it is a good idea to document somewhere that the SIGPIPE signal should be handled by the users of the library.

**Comment by singpolyma** [comment]
This is still the case and I'm not sure what is the advantage of allowing SIGPIPE and forcing every strophe user to ignore it?
