### ISSUE TITLE
Strophe XMPP::Connection inheritance example

### ISSUE THREAD

**Issue by jngd** [strophe/libstrophe#129]
I'm wondering if class XMPP::Connection in C++ wrapper is motivated to implement or inherit from. Can someone provide an example of use for that class?

Thanks in advance

**Comment by pasis** [comment]
Unfortunately, implementation of this class is missed. I can't tell for sure, but I think it hasn't been written at all. Moreover, existent c++ code may be outdated, since no one maintained it for a long time.
