### ISSUE TITLE
Could you please add unicode support ?

### ISSUE THREAD

**Issue by quanzhuo** [strophe/libstrophe#135]

**Comment by pasis** [comment]
@quanzhuo, what exactly issues you experience with unicode? Is it interface which doesn't accept `wchar_t*` or something else?

**Comment by quanzhuo** [comment]
> @quanzhuo, what exactly issues you experience with unicode? Is it interface which doesn't accept `wchar_t*` or something else?

Yes, Its interface does't accept unicode string.
ex:
```c
const char *name = xmpp_stanza_get_attribute(item, "name");
printf(" %s\n", name);
```
xmpp_stanza_get_attribute accept char* and return char*, If the name is unicode string, the output is messy code

**Comment by pasis** [comment]
I've done the following test:
1. xmpp_send creates a message where both an attribute and body have mixed unicode and english letters;
2. xmpp_send sends the message;
3. xmpp_recv receives the message and prints the attribute and body.

Both unicode strings was printed correctly with `printf()` and they had type `char*`. I couldn't reproduce your issue with multiple scenarios.

As far as I know, you can work with unicode strings as with asciiz as long as you don't break unicode letters boundaries.

**Comment by pasis** [comment]
Close as cannot reproduce.
