### ISSUE TITLE
Opportunistic IPv4/IPv6 connection

### ISSUE THREAD

**Issue by jubalh** [strophe/libstrophe#139]
Started at: https://github.com/profanity-im/profanity/issues/915

> I had IPv6 connectivity loss on my server for a while, and noticed Profanity failing to connect at all. It would be great with some kind of googley eyes behaviour, probably for each and every one of the connections it tries to establish.

> yes, this is libstrophe issue, please, open ticket there to check all possible addresses until one succeeds. Now, libstrophe checks them one by one until one only starts connecting successfully. But this is not enough if port is closed on the remote side for a particular address family.

**Comment by pasis** [comment]
The feature has been merged to master. Closing.
