### ISSUE TITLE
Is there any audio-video call support on lidstrophe?

### ISSUE THREAD

**Issue by waqarahmad84** [strophe/libstrophe#141]
I want to create a terminal based xmpp messaging and audio-video call client using c/c++. Where I am interested to use libstrophe as library. My problem is on libstrophe I found all kind of messaging and other support what I want but I can't found any audio-video call support. Now, my question is ---
1. I want to know can anybody tell me is there any calling support on libstrophe?
2. Whether libstrophe support any plugin or not?

**Comment by pasis** [comment]
1. Libstrophe doesn't provide audio-video functionality. But this is a low-level library and you can implement those in your application.

2. There is no plugins support. If you would like to implement a XEP outside of libstrophe and share it, you can create shared library.

**Comment by pasis** [comment]
Close issue.
