### ISSUE TITLE
(not libstrophe issue) help request while debugging very difficult to reproduce bug

### ISSUE THREAD

**Issue by mrkiko** [strophe/libstrophe#142]
Hi!
I am developing AGH: a project using libstrophe you can find here
https://github.com/mrkiko/agh

I am encountering this issue:
https://github.com/mrkiko/agh/issues/5

Can you help me out guys? I wasn't able to reproduce the problem. I know, this code isn't beautiful...
Any help in improving is greatly apreciated!

**Comment by pasis** [comment]
@mrkiko, I had a look at your code and didn't find the problem. Could you share with instructions how to run and check your project with the smallest effort?

**Comment by mrkiko** [comment]
@pasis I apreciate very very much your answe, really.

The problem is I wasn't able to reproduce the bug even a single time more than the one I reported, and this per se is an issue.
Still, to text the prohram you may need to install.
- ModemManager library
- libubox, libubus and UCI

And then configure an XMPP account via an UCI config file:

root@OpenWrt:~# cat /etc/config/agh_xmpp
config section 'connection'
        option node     laptop
        option domain   your_domain.com
        option password try_a_pass
        option resource coldstars
        option tcp_keepalive_interval   1
        option tcp_keepalive_timeout    60
        list controller_barejid xmpp_account_from_which_you-may_control_the_program@domain.com
        option ping_interval    120
        option ping_timeout     10
root@OpenWrt:~#

But I understand this can be an assle. If you want I may provide a ready to use OpenWRt image with all the packages compiled with debug syymbols...
Thank you very much again

**Comment by pasis** [comment]
@mrkiko, if this issue is still actual, could you check libstrophe 0.9.3 (in your ticket you mentioned 0.9.2)? Also libstrophe debug logs can help to understand execution path which is better than searching for an error in all the code.

**Comment by mrkiko** [comment]
Sorry for the long time. Unfortunately, I am no longer working on this, and can't do so in the future. Hence, I am closing this issue.
I am very grateful for your help along this. thank you!!!!
