### ISSUE TITLE
./configure syntax error on Alpine

### ISSUE THREAD

**Issue by gjabell** [strophe/libstrophe#145]
Hey all,

I'm trying to package libstrophe / libmesode for Alpine Linux, and I'm running into the error when running the generated `configure` script:

```
checking for expat... ./configure: line 12910: syntax error: unexpected word (expected ")")
```

Code around the mentioned line is:

```
if test "x$ac_cv_header_expat_h" = xyes; then :

                                    expat_LIBS="-lexpat"
                                    PC_LIBS+=($expat_LIBS)

else
  as_fn_error $? "expat not found; expat required." "$LINENO" 5

fi
```

with the `PC_LIBS+=($expat_LIBS)` being line `12910`.

Has anyone else run into a similar issue? I'm not sure whether this is a problem with Alpine or something else.

Thanks!

**Comment by gjabell** [comment]
Should also note that this doesn't seem to actually be related to expat, despite failing on that line; I have tried with both `expat` and `expat-dev` (expat development libs) installed, as well as with `libxml2` and `--with-libxml2` compiler flag, with the same result.

**Comment by pasis** [comment]
@gjabell , do you have this issue only with libmesode or with libstrophe too? libstrophe doesn't use arrays (the problem line you mentioned) for a long time. There are open issues regarding this in libmesode: profanity-im/libmesode#7, profanity-im/libmesode#11.

**Comment by gjabell** [comment]
I had the same issue with both libstrophe and libmesode (tried libstrophe after libmesode failed). I didn't find those issues yesterday for some reason, let me see if the patch in #7 works for alpine too and report back.

26.11.2019 08:41:32 Dmitry Podgorny <notifications@github.com>:

**Comment by gjabell** [comment]
Looks like alpine has the same issue as BSD, using the patch from profanity-im/libmesode#11 fixed it and allowed the configure script to complete.

**Comment by pasis** [comment]
What version of libstrophe did you checked? Versions since 0.9.0 are not affected by this issue.

**Comment by gjabell** [comment]
I had issues with 0.9.3 and 0.9.2 for both libstrophe and libmesode. Might have also been an issue with the packaging script though.

26.11.2019 14:22:23 Dmitry Podgorny <notifications@github.com>:
