### ISSUE TITLE
XEP-0384: OMEMO Encryption

### ISSUE THREAD

**Issue by Neustradamus** [strophe/libstrophe#148]
Can you add OMEMO Encryption support?
- https://conversations.im/omemo/
- https://xmpp.org/extensions/xep-0384.html

**Comment by jubalh** [comment]
OMEMO encryption is in Profanity, which uses libstrophe.

**Comment by Neustradamus** [comment]
@jubalh, it is not possible to have directly in libstrophe?
It will be better to all ^^

**Comment by jubalh** [comment]
libstrophe does not implement any XEP. Only XMPP core.

**Comment by Neustradamus** [comment]
A "libstrophe-omemo" plugin for example :)

**Comment by pasis** [comment]
@Neustradamus, As I mentioned in #152, libstrophe won't support such a XEP (due to libstrophe design). However, if we start a separated project for XEPs support, I will be happy to add OMEMO to the backlog there.

Closing the issue here.

**Comment by Neustradamus** [comment]
@jubalh: Can you see for create a module?
It will be perfect to all...

**Comment by jubalh** [comment]
@Neustradamus my dear friend.
Many of us developers have thought about doing this already. We discussed this several times in the profanity MUC etc. It's not like we don't understand the benefits of having the XEPs at one place and having a separate library for it.

What I told you was that **it will not be done in libstrophe**, nothing more nothing less.

**Comment by Neustradamus** [comment]
@jubalh: Thanks for your reply.
It is very appreciated.
