### ISSUE TITLE
Request support for c-ares instead of libresolv

### ISSUE THREAD

**Issue by dirwiz** [strophe/libstrophe#151]
Is there a chance to add c-ares support as an option instead of libresolv.  I'm already using it in curl in the same project.
https://c-ares.haxx.se/
Also on GitHub: @c-ares https://github.com/c-ares/c-ares

Thanks!

**Comment by pasis** [comment]
libstrophe supports c-ares. Configure it with `--enable-cares` to replace libresolv with c-ares. This feature will be in the next 0.10.0 release, however, it is up to package maintainers to choose either libresolv or c-ares.

**Comment by dirwiz** [comment]
That's great news!  I'm using libstrophe from source so no worries there.  Can't wait to see 0.10.0 when it gets released!
Keep up the great work!
