### ISSUE TITLE
Fix ipv6 in Windows 10

### ISSUE THREAD

**Issue by hcosmin** [strophe/libstrophe#153]
Latest Libstrophe branch fails to connect over ipv6 to a server on Windows 10.

The fix is to replace in sock.c, `int sock_connect_error(const sock_t sock)` function
`struct sockaddr sa;` with a `struct socketaddr_storage sa`.

The issue is that struct sockaddr is not guaranteed to be large enough to hold ipv6 adresses, and indeed it isn't on Windows, so getpeername(...) fails.

**Comment by pasis** [comment]
Thank you for report. Please, check the latest master branch.
