### ISSUE TITLE
Missing from field in start stream

### ISSUE THREAD

**Issue by vishwa-mke** [strophe/libstrophe#163]
The "from" field is missing during stream start, while this information is optional, it is quite important in some cases (for example in a situation where there is a need to load balance incoming XMPP requests based on their JID). It would be nice if there is a way in libstrophe to include this field at least as a configurable option, so that these kind of use cases can be fulfilled in line with the XMPP specification.

**Comment by pasis** [comment]
Thank you for pointing to this feature. It's implemented in master. `from` is sent in every `<stream>` tag over TLS(!) session.

**Comment by pasis** [comment]
And kudos to @jubalh for pointing to privacy concerns with the `from` attribute over plaintext connection.
