### ISSUE TITLE
how to set the private certificate of openssl?

### ISSUE THREAD

**Issue by TitusSun** [strophe/libstrophe#164]
Hi, below interface is not implemented. so it need to implement by oursefves?

tls_set_credentials()

or is there other place to set the credentials?

**Comment by pasis** [comment]
Hi, this interface was never used. Even if you implement this function for openssl module, you will need to create public API to allow application to pass their certificates. Something is implemented in tls_gnutls.c module, however it is not used by other code.

If you have time for this, you can implement and send pull request for this feature. Or, you can simply hardcode your certificate somewhere for testing.

**Comment by TitusSun** [comment]
@pasis  OK, thanks. if I need to implement it. I will send the request.

**Comment by pasis** [comment]
@TitusSun take a look at this branch: https://github.com/strophe/libstrophe/tree/cafile . `xmpp_conn_tls_cafile()` should do what you need. `examples/basic.c` shows a small example.

**Comment by sjaeckel** [comment]
I'm closing this as there was no action for too long.
Please re-open if you have further questions/comments.
