### ISSUE TITLE
Handle presence

### ISSUE THREAD

**Issue by serch0290** [strophe/libstrophe#165]
I am a beginner and I'm trying to make a simple client.

I'm trying to get the update presence stanza as (subscribed or available ...etc) but it doesn't work for me, 

I add mi handle: 
xmpp_handler_add(conn, handle_presence, NULL, "presence", NULL, ctx);

but I send it a presence stanza presence and I don't get the presence update, any ideas?

**Comment by jubalh** [comment]
Maybe it helps to look at https://github.com/strophe/libstrophe/tree/master/examples and https://github.com/profanity-im/profanity and https://github.com/jubalh/hedwig/blob/master/src/xmpp.c

**Comment by pasis** [comment]
@serch0290 , first of all, lets find what doesn't work. Have you enabled debug logs? They show all incoming and outgoing stanzas. This would help to see if you receive presence stanzas at all.

This example shows how to create context with printing debug logs to the terminal: https://github.com/strophe/libstrophe/blob/master/examples/basic.c .
Basically, what you need to do is:
```C
    xmpp_ctx_t *ctx;
    xmpp_log_t *log;

    log = xmpp_get_default_logger(XMPP_LEVEL_DEBUG);
    ctx = xmpp_ctx_new(NULL, log);
    /* Create connection, etc ... */
```

If you can show me the code, I will check it for mistakes.

**Comment by serch0290** [comment]
In fact, I have enabled debug logs, when I add a new friend or have a change in the list if I get the stanza and debug It prints:

xmpp DEBUG RECV: <iq id="push16659519636813614895" type="set" to="lore@serch-pc/58325268866871893072053" from="lore@serch-pc"><query xmlns="jabber:iq:roster" ver="9dcf7b35fca9346f16988b4a80e80a4ba6f36da9"><item jid="server@serch-pc" subscription="both"/></query></iq>

when I send a presence, debug it prints:

DEBUG SENT: <presence to="server@serch-pc" type="available"/>

but when i want recive send a presence stanza debug doesn't print anything and never enters my handler.

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* 
 * File:   main.c
 * Author: serch
 *
 */



#include <stdio.h>
#include <stdlib.h>
#include <strophe.h>
#include <string.h>
#include <libpq-fe.h>

struct Dispositivo{
    int idDispositivo;
    char usuario[200];
    char password[200];
    char vHost[200];
    char jid[200];
} dispositivo; 

void conn_handler(xmpp_conn_t *const conn,
                  const xmpp_conn_event_t status,
                  const int error,
                  xmpp_stream_error_t *const stream_error,
                  void *const userdata);

void sendPresencia(xmpp_conn_t *const conn, 
                     xmpp_ctx_t *ctx, char *tipo);

void generarRoster(xmpp_conn_t *const conn, 
                   xmpp_ctx_t *ctx);

int handle_reply(xmpp_conn_t *const conn,
                 xmpp_stanza_t *const stanza,
                 void *const userdata);

int handle_presence(xmpp_conn_t *const conn,
                              xmpp_stanza_t *const stanza,
                              void *const userdata);
/*
 * 
 */
int main(int argc, char** argv) {
    xmpp_ctx_t *ctx;
    xmpp_conn_t *conn;
    xmpp_log_t *log;
    /*if (argc != 3) {
        fprintf(stderr, "Usage: active <jid> <pass>\n\n");
        return 1;
    }*/
    /* initialize lib */
    xmpp_initialize();
    /* pass NULL instead to silence output */
    log = xmpp_get_default_logger(XMPP_LEVEL_DEBUG);
    
    /* create a context */
    ctx = xmpp_ctx_new(NULL, log);
    
    /* Se realiza la conexión al servidor XMPP */
    conn = xmpp_conn_new(ctx);
    char vhost_aux[] = "serch-pc";
    char usuario[] = "lore";
    char password[] = "lore";
    char recurso[] = "MiDispositivo";
    strcpy(dispositivo.vHost, vhost_aux);
    strcpy(dispositivo.usuario, usuario);
    strcpy(dispositivo.password, password);
    strcat(dispositivo.jid, dispositivo.usuario); 
    strcat(dispositivo.jid, "@");
    strcat(dispositivo.jid, dispositivo.vHost);
   
    /* setup authentication information */
    xmpp_conn_set_jid(conn, dispositivo.jid);
    xmpp_conn_set_pass(conn, dispositivo.password);

    /* initiate connection */
    xmpp_connect_client(conn, dispositivo.vHost, 5222, conn_handler, ctx);
    
    /* start the event loop */
    xmpp_run(ctx);

    /* release our connection and context  */
    xmpp_conn_release(conn);
    xmpp_ctx_free(ctx);

    /* shutdown lib */
    xmpp_shutdown();
    
    return (EXIT_SUCCESS);
}


void conn_handler(xmpp_conn_t *const conn,
                  const xmpp_conn_event_t status,
                  const int error,
                  xmpp_stream_error_t *const stream_error,
                  void *const userdata)
{
    (void)error;
    (void)stream_error;
    xmpp_ctx_t *ctx = (xmpp_ctx_t *)userdata;
    switch(status){
        case XMPP_CONN_CONNECT:
           fprintf(stderr, "DEBUG: connected\n");
           xmpp_handler_add(conn, handle_presence, NULL, "presence", NULL, ctx);
           sendPresencia(conn, ctx, "available");
           generarRoster(conn, ctx);
         break;
        case XMPP_CONN_FAIL:
           fprintf(stderr, "DEBUG: FAIL\n");
           xmpp_stop(ctx);
         break;
        case XMPP_CONN_DISCONNECT:
          fprintf(stderr, "DEBUG: DISCONECT\n");
          xmpp_stop(ctx);
         break;
    }
}

void sendPresencia(xmpp_conn_t *const conn, 
                     xmpp_ctx_t *ctx,
                     char *type){
  xmpp_stanza_t *query;
  query = xmpp_presence_new(ctx);
  xmpp_stanza_set_type(query, type);
  xmpp_stanza_set_to(query, "server@serch-pc");
  xmpp_send(conn, query);
  xmpp_stanza_release(query);
  
}//Fin del metodo

void generarRoster(xmpp_conn_t *const conn, 
                   xmpp_ctx_t *ctx){
    
   xmpp_stanza_t *iq, *query;
   
   /* create iq stanza for request */
    iq = xmpp_iq_new(ctx, "get", "roster1");
    query = xmpp_stanza_new(ctx);
    xmpp_stanza_set_name(query, "query");
    xmpp_stanza_set_ns(query, XMPP_NS_ROSTER);
    
    xmpp_stanza_add_child(iq, query);

    /* we can release the stanza since it belongs to iq now */
    xmpp_stanza_release(query);

    /* set up reply handler */
    xmpp_handler_add(conn, handle_reply, XMPP_NS_ROSTER, "iq", NULL, ctx);
    //xmpp_handler_add(conn, handle_reply, XMPP_NS_ROSTER, "iq", "set", ctx);

    /* send out the stanza */
    xmpp_send(conn, iq);

    /* release the stanza */
    xmpp_stanza_release(iq);
}//Fin del metodo generarRoster

int handle_reply(xmpp_conn_t *const conn,
                 xmpp_stanza_t *const stanza,
                 void *const userdata)
{
    xmpp_stanza_t *query, *item;
    const char *type, *name;
    xmpp_ctx_t *ctx = (xmpp_ctx_t *)userdata;
    (void)userdata;

    type = xmpp_stanza_get_type(stanza);
    if (strcmp(type, "error") == 0)
        fprintf(stderr, "ERROR: query failed\n");
    else {
        query = xmpp_stanza_get_child_by_name(stanza, "query");
        printf("Roster:\n");
        for (item = xmpp_stanza_get_children(query); item;
             item = xmpp_stanza_get_next(item))
            if ((name = xmpp_stanza_get_attribute(item, "name")))
                printf("\t %s (%s) sub=%s\n", name,
                       xmpp_stanza_get_attribute(item, "jid"),
                       xmpp_stanza_get_attribute(item, "subscription"));
            else
                printf("\t %s sub=%s type: %s\n", xmpp_stanza_get_attribute(item, "jid"),
                       xmpp_stanza_get_attribute(item, "subscription"), type);
        printf("END OF LIST\n");
    }

    return 1;
}

int handle_presence(xmpp_conn_t *const conn,
                 xmpp_stanza_t *const stanza,
                 void *const userdata)
{
    xmpp_stanza_t *query, *item;
    const char *type, *name;
    xmpp_ctx_t *ctx = (xmpp_ctx_t *)userdata;
    
    (void)userdata;

    type = xmpp_stanza_get_type(stanza);
    if (strcmp(type, "error") == 0)
        fprintf(stderr, "ERROR: query failed\n");
    else {
        printf("\t type: %s\n", type);
    }

    return 1;
}

**Comment by pasis** [comment]
@serch0290 , you need to send initial presence as presence stanza with no `to` and `type` attributes. Try this code instead of your `sendPresencia` function:
```C
void sendPresencia(xmpp_conn_t *const conn,
                     xmpp_ctx_t *ctx,
                     char *type){
  xmpp_stanza_t *query; 

  query = xmpp_presence_new(ctx);
  if (strcmp(type, "available") != 0) {
    xmpp_stanza_set_type(query, type);
  }
  xmpp_send(conn, query);
  xmpp_stanza_release(query);
  
}//Fin del metodo
```

Also a small hint: libstrophe provides API to work with JID strings. So, you can create jid string with 1 call:
```C
char *jid = xmpp_jid_new(ctx, "user", "domain", "resource"); /* You can pass NULL to parts you don't need */
...
xmpp_free(ctx, jid); /* Note that you need to free allocated string with xmpp_free() */
```

**Comment by serch0290** [comment]
Thanks so much for your solution, if i work with that
Thank for the hint.
