### ISSUE TITLE
xmpp_ctx_set_timeout does not work ? (stophe 0.9.3)

### ISSUE THREAD

**Issue by dev31337** [strophe/libstrophe#167]
Setting xmpp_ctx_set_timeout(ctx,50) has no effect on xmpp_run(ctx) which never times out (never returns).

**Comment by dev31337** [comment]
Solved by using undocumented xmpp_run_once() instead :)

**Comment by pasis** [comment]
`xmpp_run()` runs the event loop until `xmpp_stop()` is called. `xmpp_ctx_set_timeout()` controls timeout for I/O event notification within `xmpp_run()` -- it doesn't affect `xmpp_run_once()`.

You need to choose between `xmpp_run()` and `xmpp_run_once()` depending on your use-case. `examples/bot.c` shows how to write a program with `xmpp_run()`.
