### ISSUE TITLE
XEPs support page

### ISSUE THREAD

**Issue by Neustradamus** [strophe/libstrophe#17]
It will be a good idea if there was a page with actual XEPs supported (with versions) by libstrophe.

Example:

https://prosody.im/doc/xeplist

http://www.process-one.net/en/ejabberd/protocols/
http://www.ejabberd.im/protocols

https://trac.gajim.org/wiki/GajimXEPSupport

https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by pasis** [comment]
Libstrophe implements the xmpp core and XEP-0114 as I know. Such a page would be almost blank, so I don't see any point in creating it.
