### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by andrey-utkin** [strophe/libstrophe#171]
Hi,

Thanks for fixing the libressl compat in https://github.com/strophe/libstrophe/commit/acced31192931cfff480ba66be5e634f906a1beb  and getting in touch with us at Gentoo in https://bugs.gentoo.org/744127#c8 .

You said there's going to be a future minor release. That would be nice indeed.

It's not a problem if you're not going to issue a new release soon - in Gentoo we can patch upstream, but having an upstream release simplifies things for us of course. So please at least let me know when a new release is going to happen.

Thanks in advance.

**Comment by pasis** [comment]
Hi, 0.10.1 is out: https://github.com/strophe/libstrophe/releases/tag/0.10.1

**Comment by andrey-utkin** [comment]
Much appreciating your responsiveness!

Just FYI, seems LibreSSL is going to be being discontinued in Gentoo. I loosely agree with this proposal.
https://archives.gentoo.org/gentoo-dev/message/9a92320c599e63c8c18b2ed29050f22f
