### ISSUE TITLE
Add stdcall call method macro 

### ISSUE THREAD

**Issue by 36k-wild-monkey** [strophe/libstrophe#174]
I want to use it for third-party languages, but only supports stdcall callbacks

**Comment by pasis** [comment]
Could you elaborate on this request? Do you mean adding `__stdcall` around API? Which language and OS it is required for? Do you have examples from other libraries?

**Comment by sjaeckel** [comment]
I'm closing this as there was no action for too long.
Please re-open if you have further questions/comments.
