### ISSUE TITLE
Is it possible to build libstrophe for iOS?

### ISSUE THREAD

**Issue by Igorsnaki** [strophe/libstrophe#180]
Hi all, 

Is it possible to build libstrophe for iOS ?  ( And use it for implement xmpp chat inside iOS application? 
Could you please point to documentation? 
Thank you in advance. 

p.s. I saw this project https://github.com/play-co/libstrophe-ios 
but it contains old architectures and doesn't contain x86_64 and arm64

**Comment by pasis** [comment]
Hi, unfortunately, there is no documentation how to build libstrophe for iOS. All I know is that this is possible and people have done this. I'm not an expert in iOS, so I would suggest to consult with an expert, how to setup a build system.

From an iOS developer I heard once that "cocoa pods" is a thing for adding libraries to a project. And there are already pods for openssl and expat, so maybe you will have a luck with making a pod for libstrophe as well.

**Comment by sjaeckel** [comment]
I'm closing this as there was no action for too long.
Please re-open if you have further questions/comments.
