### ISSUE TITLE
cannot connect when vpn active

### ISSUE THREAD

**Issue by ThinkerOfThoughts** [strophe/libstrophe#181]
When my vpn is running, the example bot from the repository cannot connect to the server. Pidgin works fine and is able to connect to the account I made for the bot. But the bot cannot. If I turn my vpn off, everything works fine. Any help would be appreciated.

If it helps, im running Ubuntu 20.04 LTS, the vpn is Private Internet Access.

When I run the example bot, I get the following

~$./bot <bots username>@chatterboxtown.us <bots password>
xmpp DEBUG sock_connect() to chatterboxtown.us:5222 returned 3
xmpp DEBUG Attempting to connect to chatterboxtown.us
xmpp DEBUG connection failed, error 111
xmpp DEBUG Closing socket.
DEBUG: disconnected
event DEBUG Stopping event loop.
event DEBUG Event loop completed.

**Comment by pasis** [comment]
I would compare DNS behavior in these 2 scenarios. Check this line for the working case:
```
xmpp DEBUG sock_connect() to chatterboxtown.us:5222 returned 3
```
Is address the same without VPN? If yes, you can also run sniffer (e.g. wireshark) and compare both scenarios, for example, whether IP addresses are the same.

**Comment by ThinkerOfThoughts** [comment]
Did as suggested, with the vpn and without that line is the same.
Without the vpn, wireshark shows it sending a packet to that ip of the chatterboxtown server, gets a reply, sends another, and so on. All with the DNS protocol. Eventually it switches to ipv6 addresses and TCP.
However, with vpn, it sends a packet to the same ip, doesn't get a response, sends another, then gives  up. all with the TCP protocol which is the connection type my vpn uses.
