### ISSUE TITLE
SO versioning not done correctly

### ISSUE THREAD

**Issue by sjaeckel** [strophe/libstrophe#190]
The SONAME is not correctly versioned.

Problem
-----------
The library gets always installed as `libstrophe.so.0.0.0` which is somehow not correct and I'm a bit surprised that this didn't come up yet from some package maintainers.

Solution options
---------------------
1. Ignore it and continue until someone complains (or declare that versioning is rolling and we'll never do SONAME versioning)
2. start doing it "properly"/"as expected"

I could live with both :)

Maybe some of the distro maintainers or users also want to give their comments on this second topic ... @fantomfp (fedora) @a02c1175-5220-4e75-b7a1-18e20548305f (debian) @jubalh (profanity) @debxwoody (profanity)

**Comment by jubalh** [comment]
> which is somehow not correct and I'm a bit surprised that this didn't come up yet from some package maintainers.

my guess is that people never complained because existing API never changed (AFAIK), only new things being added. So it wasn't a high prio/problem for people.

I maintain libstrophe in openSUSE since 2015, from that point of view I would obviously prefer to have proper library versioning in so file :)

**Comment by fantomfp** [comment]
> ## Solution options
> 
>     1. Ignore it and continue until someone complains (or declare that versioning is rolling and we'll never do SONAME versioning)
> 
>     2. start doing it "properly"/"as expected"
> 
I maintain libstrophe in Fedora since few months, so I didn't do any package update yet. But, the good answer for this problem is: what are you going to do in libstrophe. If you want to start to try new things and break API, that's fine but please use soname versionning :)

**Comment by sjaeckel** [comment]
@jubalh @fantomfp maybe you can have a look at #194 try out what your distro toolchain says when you rebuild with SO versioning enabled and let me know if that's fine for you or if it requires further changes!?
