### ISSUE TITLE
Continuous Bosh Request

### ISSUE THREAD

**Issue by itsaboutcode** [strophe/libstrophe#210]
We are seeing continuous requests to bosh with this payload

```
<body rid="375773228" sid="a63c9996f13549a85ae2cd04c446cc16c261e95b" xmlns="http://jabber.org/protocol/httpbind"><a h="252" xmlns="urn:xmpp:sm:3"/></body>
```

Not sure what's causing it but it's making our application slow.  Any idea why it's making these requests and how we can stop it?

**Comment by nosnilmot** [comment]
`<a xmlns='urn:xmpp:sm:3' h='N'/>` is an acknowledgement sent as part of [XEP-0198: Stream Management](https://xmpp.org/extensions/xep-0198.html). Is the `N` changing? in your example it is 252, it would be increasing if other stanzas are being handled.

Are there continuous `<r xmlns='urn:xmpp:sm:3'/>` being received from the server?

This could be normal behaiviour of XEP-0198, or it could be a bug, depending on the answers above, but if you just want to disable stream management you can set flag `XMPP_CONN_FLAG_DISABLE_SM` using `xmpp_conn_set_flags()`.
