### ISSUE TITLE
Resending of old messages on reconnect

### ISSUE THREAD

**Issue by mdosch** [strophe/libstrophe#215]
I am using the debian package of libstrophe 0.12.2 with profanity master.

When I wake up my laptop from suspend old messages (to MUCs, didn't experience this with 1-1 yet) are often resend on reconnect. Not on every reconnect and sometimes the messages are already days old and there have been several reconnects since the message was originally sent an it is resend.

Somehow I suspect the new stream management.

**Comment by sjaeckel** [comment]
Is this still an issue or can this be closed?

**Comment by mdosch** [comment]
I disabled sm for now so I don't know whether this is still an issue with sm enabled.

**Comment by sjaeckel** [comment]
OK, SM is on per default and it seems you're the only one experiencing this issue as nobody else reported it yet.

I'm closing this now, feel free to re-open if you feel like you want to give it a try and it still happens, but then please provide debug logs.

**Comment by sjaeckel** [comment]
Can you please try out the latest master version?

**Comment by mdosch** [comment]
Unfortunately I will have little time until 16.02. so I can't promise I can do this earlier.


Am 31. Januar 2024 16:28:55 UTC schrieb Steffen Jaeckel ***@***.***>:
>Can you please try out the latest master version?
>

**Comment by mdosch** [comment]
I enabled sm in profanity and had many reconnects on two machines over the last week and didn't experience this problem anymore, therefore I'm closing the issue.
