### ISSUE TITLE
specify the network interface from which the xmpp traffic will be sent

### ISSUE THREAD

**Issue by Anisel** [strophe/libstrophe#220]
Specify the network interface from which the xmpp traffic will be sent

## Expected Behavior

when using the libstrophe function to set up a connection like following 
/* create a connection */
conn = xmpp_conn_new(ctx);
is it possible to specify from which network interface the xmpp traffic will be sent through

**Comment by sjaeckel** [comment]
There's a `SO_BINDTODEVICE` option that can be set via the `setsockopt()` API.

You should be able to do this by creating your own `xmpp_sockopt_callback` that calls `setsockopt()` with the correct arguments

https://github.com/strophe/libstrophe/blob/37555868f656cbe5aa513ed8008028e8dffe26c2/strophe.h#L321-L351
https://github.com/strophe/libstrophe/blob/37555868f656cbe5aa513ed8008028e8dffe26c2/strophe.h#L386-L387
