### ISSUE TITLE
Error logging in to remote selfhosted server

### ISSUE THREAD

**Issue by CalmTechie** [strophe/libstrophe#240]
Initial issue: https://github.com/profanity-im/profanity/issues/1960

At the instance of @sjaeckel (https://github.com/profanity-im/profanity/issues/1960#issuecomment-1999378613), I transfer the issue hither.

### Summary:

Logging in to the selfhosted prosody server using profanity (which utilizes libstrophe) causes error. Profanity logs:
https://dormant.observer/-W5N6VNrwES

Tried both 0.13.0 and 0.13.1 lib versions.

**Comment by CalmTechie** [comment]
Here's server debug logs. It seems that tls 1.3 **is** in use.

https://dormant.observer/-Xar8pqpuYp

**Comment by sjaeckel** [comment]
Hmm, server debug logs are not really useful here. It only looks like in the successful example the `PLUS` variant was not used.

Can you provide debug logs from dino and yaxim?

Can I somehow test against your server? Can you maybe provide your config?

**Comment by CalmTechie** [comment]
Can't find how to debug yaxim (server logs tells that it uses plain auth mechanism).

Dino's log quite verbose. Here's raw debug log file:

https://dormant.observer/-TcNcSgeqHx

Regarding server configuration: what do you exactly need? Prosody config file is more or less default. Here it is:

https://dormant.observer/-K49g7nckdA

conf.d doesn't contain any additional tweaks.

**Comment by sjaeckel** [comment]
Which version of prosody are you running? Is it really 0.11.2 as reported when querying the server version? If yes, can you please update to latest stable and try again? 

All the other clients that succeed in your tests don't use and/or support SCRAM-*-PLUS and AFAIK @mdosch runs latest prosody and uses SCRAM-*-PLUS successfully with libstrophe/profanity.

**Comment by mdosch** [comment]
Yep, works with prosody trunk on my server:

> 2024-03-20T18:08:48.874351+01: xmpp: DBG: handle SCRAM-SHA-1-PLUS (challenge) called for challenge
> 2024-03-20T18:08:48.927806+01: xmpp: DBG: handle SCRAM-SHA-1-PLUS (challenge) called for success
> 2024-03-20T18:08:48.927825+01: xmpp: DBG: SASL SCRAM-SHA-1-PLUS auth successful

**Comment by CalmTechie** [comment]
Can not currently install modern version of prosody. Let's presume it's server malfunction. Thank you for you help.

**Comment by sjaeckel** [comment]
Feel free to reopen once you could update prosody and this persists.

FYI Currently there's no work around for profanity, besides using an older version of libstrophe.
