### ISSUE TITLE
Build conflict with openssl 3.2 tls_free

### ISSUE THREAD

**Issue by matthias-hmb** [strophe/libstrophe#242]
### Stituation
Openssl 3.2 adds tls_free function:
https://github.com/openssl/openssl/blob/master/ssl/record/methods/tls_common.c#L1450

### Problem
A static build with libstrophe will end up in an error:
```
bin/ld: libssl.a(libssl-lib-tls_common.o): in function `tls_free' .../openssl-3.2.1/ssl/record/methods/tls_common.c:1456: multiple definition of `tls_free'; .../libstrophe.a(libstrophe_la-tls_openssl.o):tls_openssl.c:(.text+0x11dc): first defined here
```
Happens only on static build against libstrophe (no idea, why not with dynamic lib)
... but you should claim, that you invented the name first. ;)

**Comment by sjaeckel** [comment]
That's a very common problem with static libraries and one that can't be fixed AFAIK.

For that reason the usual way to use a library is via the dynamic library, where one can have public and private symbol names.

https://github.com/strophe/libstrophe/blob/4d59a9fe452266d5c0c12b6fe5e6136ad1cea87b/Makefile.am#L41

The `-export-symbols-regex '^xmpp_'` declares all symbols of libstrophe that start with `xmpp_` as public, all the others symbols are hidden in the dynamic library.

There exist some ways to rename those symbols inside the library, which can be found when searching for it on your preferred search engine. A quick search revealed https://lib.rs/crates/armerge which I haven't used yet, but looks promising.

I'm closing this, as we can't really solve this, besides by namespacing also the private symbols, but I really would prefer to not do that.
