### ISSUE TITLE
ooconnection.cpp missing

### ISSUE THREAD

**Issue by h0ru5** [strophe/libstrophe#25]
blocking #24 
the C++ API is defining 3 classes in the ``strohepp.h``
2 of them are implemented: ``Context`` and ``Stanza``, but ``Connection`` is missing.
Did you just forget to ``git add`` the file?

**Comment by pasis** [comment]
C++ implementation isn't finished and officially not provided. Without person who would continuously support C++ code, libstrophe remains C library.

**Comment by Ltrlg** [comment]
Four years later, it has still not been implemented… Maybe the partial C++ support should be moved to a dedicated branch and removed from master until someone will work on it? Or at least add a big warning in `strophepp.h`?

**Comment by jubalh** [comment]
@Ltrlg I'm quite happy that after 4 years finally someone appears who you volunteers to maintain C++ support in libstrophe. Thanks a lot for this!
Please submit your pull request in the next days.

**Comment by Ltrlg** [comment]
I am not planning to work on it (well, I might have reasons to contribute in the near future, but that was not my point).

I was just saying that
  1. the current state is suboptimal in making people think that there is support while there isn't
  2. while the partial implementation may not be completed right now, there are better ways to convey the “unsupported” information than what this library currently does

Just consider how confusing it is right now: 
  - strophepp.h is included in master without any warnings;
  - strophepp.h is not excluded from Github release assets (which AFAICT is the closest to an official download);
  - no indication of the status in the README;
  - way too prominent in generated docs.

**Comment by jubalh** [comment]
I understood your points.
What triggered me was: "Four years later, it has still not been implemented… "

**Comment by pasis** [comment]
@Ltrlg, as you suggested, I removed C++ files in master.
