### ISSUE TITLE
xml parsing uses a lot of memory.(expat)

### ISSUE THREAD

**Issue by curse666** [strophe/libstrophe#46]
Xml parsing uses a lot of memory.
For example, feed parser to 300 bytes of text, xml parsing uses more than 10k bytes.
This behavior caused by character detection mechanism of expat.
Expat don't detects character at once. Characters are detected little by little(1 character~) so a group of text has meny stanza information.
Stanza information is sufficient if one for a group of text.

**Comment by pasis** [comment]
Fixed by #47.
