### ISSUE TITLE
XML namespaces not properly supported

### ISSUE THREAD

**Issue by cwtitan** [strophe/libstrophe#51]
libstrophe currently only supports using the "stream" prefix for stream namespace elements, and does not support prefixes for any other namespaces. While most XMPP software uses prefix-free canonicalization, this is not required by the XMPP spec and any software which uses prefixed namespaces will not trigger the correct handlers.

For example, the following stanza is valid XML and conforms to the XMPP spec:

```xml
<iq type='get' id='id123' to='juliet@capulet.lit/balcony'>
	<v:query xmlns:v='jabber:iq:version'/>
</iq>
```

However, the example bot.c will not respond to the iq as libstrophe considers the v:query element to have an xmlns:v attribute, so the default handling of looking for "xmlns" to determine the namespace fails.

It is also legal according to sections 4.8.2 and 4.8.5 to use a prefix other than "stream" for the stream namespace (i.e. <s:stream xmlns:s="...">) or even prefix-free canonicalization for both the stream and the "jabber:client" namespaces. libstrophe applications fail to connect to a server that uses either of these styles.

**Comment by pasis** [comment]
Fixed by #52.
