### ISSUE TITLE
Support for in-band registration

### ISSUE THREAD

**Issue by neonthe1way** [strophe/libstrophe#54]
I was searching for a way to connect to the server without authentication, for my custom registration module. I was not able to do it and later found from this URL "https://groups.google.com/forum/#!msg/strophe/wGeP3_HJUME/pSvAR-FtrO8J" that inband registration itself is not supported.

Is support added for this or is there a way to connect without providing the jid and password

**Comment by pasis** [comment]
One feature which will be added in v0.9 is connection to a server without authentication. Also, sources will contain an example `examples/register.c` with simple implementation of [XEP-0077 (In-Band Registration)](https://xmpp.org/extensions/xep-0077.html).

You can follow the progress in branch xep-0077 (currently unfinished and dirty patch.)

**Comment by jubalh** [comment]
@pasis did this ever happen?

**Comment by pasis** [comment]
The example is in master. It can be used to register with servers that don't require some tricky verification.
