### ISSUE TITLE
libstrophe for android  

### ISSUE THREAD

**Issue by Infywebrtcdev1** [strophe/libstrophe#57]
If any know how to build this library for android .Plz let me know the step to build.

**Comment by pasis** [comment]
For reference: http://forum.openframeworks.cc/t/ofxxmpp-on-android/16755
Author of the post mentioned that could build libstrophe for android.

**Comment by pasis** [comment]
Please, check https://groups.google.com/forum/#!topic/libstrophe/KwVN7vZ_onM for the How-to.

**Comment by pasis** [comment]
For reference: http://stackoverflow.com/questions/4769020/android-and-xmpp-currently-available-solutions/28961629#28961629
This post contains makefile for Android with openssl support.
