### ISSUE TITLE
Can't compile with OpenSSL in a staged directory

### ISSUE THREAD

**Issue by daveismith** [strophe/libstrophe#58]
I'm trying to build Strophe in isolation on my build server and need to build all dependencies as part of my build process. This includes OpenSSL. When I try to compile strophe, it's detecting that OpenSSL is available, but it isn't updating the CFLAGS to handle the includes. Patch is below

--- libstrophe-0.8.7/Makefile.am	2014-10-30 22:13:49.000000000 -0400
+++ libstrophe-0.8.7_new/Makefile.am	2015-05-15 10:40:39.739164777 -0400
@@ -6,6 +6,7 @@
 PARSER_CFLAGS=@PARSER_CFLAGS@
 PARSER_LIBS=@PARSER_LIBS@

+SSL_CFLAGS = @openssl_CFLAGS@
 SSL_LIBS = @openssl_LIBS@

 STROPHE_FLAGS = -I$(top_srcdir)
@@ -14,7 +15,7 @@
 ## Main build targets
 lib_LTLIBRARIES = libstrophe.la

-libstrophe_la_CFLAGS = $(STROPHE_FLAGS) $(PARSER_CFLAGS)
+libstrophe_la_CFLAGS = $(STROPHE_FLAGS) $(SSL_CFLAGS) $(PARSER_CFLAGS)
 libstrophe_la_LDFLAGS = $(SSL_LIBS) $(PARSER_LIBS)
 # Export only public API
 libstrophe_la_LDFLAGS += -export-symbols-regex '^xmpp_'

**Comment by pasis** [comment]
This issue was fixed in Jan: @239d365ea17a08c22fc64372fe3f8a501fa18c49
