### ISSUE TITLE
Cross Compile Cannot find ssl.h

### ISSUE THREAD

**Issue by robertghobson** [strophe/libstrophe#61]
I've tried to set the library paths and even modify src/tls.openssl.c to point to the ssl.h file with no joy.  Any hints? 

src/tls_openssl.c:24:25: error: openssl/ssl.h: No such file or directory

Thanks,

-R

**Comment by pasis** [comment]
I leave this link for reference: http://www.dd-wrt.com/phpBB2/viewtopic.php?t=69219&view=next&sid=008a8af1df9706276faf11ff19ed638f .

If you still try to build it. There is no enough information to say what is wrong with your setup. Are you sure you have openssl built and installed for the target platform? If you installed only environment for cross compiling you just don't have openssl.

Anyway, you always can build libstrophe without TLS support, but your xmpp messages will be sent as plain text. If you replace `src/tls_openssl.c` with `src/tls_dummy.c` in Makefile.am you will disable tls support and won't need openssl to build or run libstrophe.

**Comment by pasis** [comment]
Close due to inactivity.
