### ISSUE TITLE
Libtool failing to build shared library on Cygwin

### ISSUE THREAD

**Issue by boothj5** [strophe/libstrophe#78]
As described at: https://github.com/boothj5/profanity/issues/692#issuecomment-164314012

A proposed fix is in a `libtool-fix` branch at: https://github.com/strophe/libstrophe/commit/6f612d4f4d2fd9f00c93986d97ebfee1256a1ff4

I thought I'd raise an issue rather than commit to master as I'm not sure this is the right way to fix it, so any feedback welcome.

**Comment by pasis** [comment]
Your solution looks fine. I looked over few resources and it is recommended or at least acceptable way. I'll check your patch on linux later and merge if it doesn't cause problems.

**Comment by pasis** [comment]
Merged, sorry for delay.
