### ISSUE TITLE
Use all known hosts instead of one with the lowest priority

### ISSUE THREAD

**Issue by pasis** [strophe/libstrophe#89]
Resolver needs an interface to return all resolved addresses. xmpp_connect_client() should use addresses sorted by priority.
Reference: boothj5/profanity#822

**Comment by changeway** [comment]
Hi,
I meet this issue in version 0.8.7 and add some code for the DNS-SRV list.
I took some time migrate my old code for current sock code. 
Not well tested, and also did not test in Win32 environment.
Could anyone help review and test my code?
https://github.com/changeway/libstrophe/commit/8813e9a430466269314e81f3576e24e01116c331

Also, I add sock_connect() to check the result list if able to connect with. 
I'm not sure if this is necessary.
Thanks.

**Comment by pasis** [comment]
Hello,
Your patch implements general idea, but if you want to merge it to the upstream I would like you to make some changes.

 * Don't use `malloc()`, all allocations must be done via `xmpp_alloc()`. There are 2 ways to achieve this: preallocation for fixed number of results in `xmpp_connect_client()` or passing `ctx` to the resolver to use `xmpp_alloc()` directly. 2nd approach is easier to implement, but it has issue with `tests/test_resolver.c` (therefore, the test should be disabled in Makefile.am until it is rewritten).

 * Assuming the 2nd approach is used, I'd suggest interface (you can play with names, but the idea is that public interface should have namespace "resolver_" and try to keep var names short):
```
/* don't create separated structure for specific list,
   maybe we will have linux kernel style lists in the future. */
typedef struct resolver_srv_rr_struc {
    uint16_t priority;
    uint16_t weight;
    uint16_t port;
    char target[MAX_DOMAIN_LEN];
    resolver_srv_rr_struc *next;
} resolver_srv_rr_t;

/* This function allocates all elements including the 1st one. (*srv_rr_list) is the result */
int resolver_srv_lookup_buf(xmpp_ctx_t *ctx, const unsigned char *buf, size_t len,
                            resolver_srv_rr_t **srv_rr_list);

int resolver_srv_lookup(xmpp_ctx_t *ctx, const char *service, const char *proto,
                        const char *domain, resolver_srv_rr_t **srv_rr_list);
```

* Make simple insertion in `resolver_srv_lookup_buf()` and move sorting to a separated function and call it when you have all elements in the list. This will make code easier to read and we don't need optimization to sort up to 5 elements in a list, so use a simple bubble sort.
```
*srv_rr_list = NULL;
for (i = 0; i < header.ancount; ++i) {
    ...
    rr = xmpp_alloc(ctx, sizeof(*rr));
    /* fill rr */
    rr->next = *srv_rr_list;
    *srv_rr_list = rr;
}
...
resolver_srv_rr_list_sort(*srv_rr_list);
```

 * Your change to `resolver_win32_srv_lookup()` will not work. I'd suggest to make a trick in `resolver_srv_lookup()` (I don't want to change the WIN32 code, because I can't support it without a win32 maintainer):
```
rr = xmpp_alloc(ctx, sizeof(*rr));
rr->next = NULL;
set = resolver_win32_srv_lookup(fulldomain, rr->target, sizeof(rr->target), &rr->port);
if (set) *srv_rr_list = rr;
else xmpp_free(ctx, rr);
```

If you have any problem or don't have time / don't want to implement this let me know.

**Comment by changeway** [comment]
Thanks,
I'll try to fix the code to follow @pasis  comment,
and pass ctx to the resolver.

**Comment by changeway** [comment]
Hi @pasis ,
I fixed my code and did more test, it should work well.
Could you please review my code again?
Thank you.
https://github.com/changeway/libstrophe/commit/1ba23a89037420fb66b4dbd70ec5216afacf45de

and I still think that only use sock_connect() to check the xmpp server connection is not good enough.
If the first priority server is fail to connect, and the second priority server work well and able to connect. In this situation. the xmpp-client keep try the first priority server, but never try the second one. No connect fail back.

**Comment by pasis** [comment]
Hi,

I will look at your patch in details later (in 1-few days). What I see at the moment is that you don't need to allocate first list element in conn.c. All allocation should be done inside resolver.c and preferably in one place.  Just use my example of insertion and don't move it to a separate function, because actual insertion is just 2 lines.

Since all allocation is in resolve.c deallocation should be there as well. This will be one more step to encapsulation. You don't have to do this right now (see next part of me comment).

If your code works I can merge it after you fix list allocation/insertion according to 1st paragraph. And we can refactor it later.

PS thanks for your work.

**Comment by pasis** [comment]
@changeway, I'm going to merge your patch as is and make few fixes. The fix is in 14066d0bff8d5bd88d1956604c0dbc200006a9d5 and I will land it soon. Please, let me know if something is wrong.

**Comment by pasis** [comment]
Patch is in master. Close.

**Comment by changeway** [comment]
Thanks for fix my code. 
I used sock_connect() to have a quick try of the list first, then start _conn_connect(). Use _conn_connect() to check the list could be better, but _conn_connect() could not return immediately in my environment. (I have some fake dns/ip to in the DNS-SRV list).

Anyway, the resolver become better.  :)
