### ISSUE TITLE
How about moving to cmake?

### ISSUE THREAD

**Issue by kassak** [strophe/libstrophe#9]
I wrote cmake build script for my fork of libstrophe.
Would you like to have it here?
It would make vs2008 directory obsolette, will add support of other targets.

**Comment by daveismith** [comment]
autotools tends to have better support for cross compilation. I know I prefer it because of that.

**Comment by pasis** [comment]
libstrophe doesn't have a maintainer to keep cmake files updated. Personally I would prefer autotools, because I'm not familiar with cmake.
