### ISSUE TITLE
please provide a proper release tarball.

### ISSUE THREAD

**Issue by rofl0r** [strophe/libstrophe#99]
it's a PitA to require the users to generate the configure script themselves and have them install the right versions of autoconf and automake.

more info:
https://github.com/sabotage-linux/sabotage/wiki/Why-github-downloads-suck

**Comment by pasis** [comment]
Starting with 0.9.1, tarballs are provided on the Releases page.

**Comment by rofl0r** [comment]
thanks a lot !
